spring:
  application:
    name: Task Manager

  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,logger,beans,mappings
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    description: A simple task management application built with Spring Boot.
    version: 1.0.0
    author: Emil Akbarov

app:
  name: Task Manager
  version: 1.0.0
  max-tasks-per-page: 10